name: "Release"

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.0'
          check-latest: true

      - name: Download Modules
        run: go mod download

      - name: Test
        run: go test -race -cover -shuffle=on ./...
        working-directory: ${{ inputs.dir }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        id: setup
        uses: actions/setup-go@main
        with:
          go-version: '1.20.0'
          check-latest: true

      - name: Download Modules
        run: go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1
          args: --timeout=5m

  release:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Needed to create git tag.
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0

      - name: Get version
        id: get_version
        run: |
          version=$(git describe --abbrev=0 --match "v*.*.*" || echo "v1.0.0")
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Compute Next version
        uses: technicallyjosh/next-version-action@v1
        id: version
        with:
          version: ${{ steps.get_version.outputs.version }}
          type: minor

      - name: Create Version Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version.outputs.next_version }}

      - name: Hub login
        uses: docker/login-action@v2
        with:
          username: hojasdemanzano
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            hojasdemanzano/tr-action:${{ steps.version.outputs.next_version }}
            hojasdemanzano/tr-action:latest
